import mongoose from "mongoose";

const productFeedSchema = new mongoose.Schema({
  item_code: { type: String },
  position_name: { type: String },
  position_name_ukr: { type: String },
  search_queries: { type: String },
  search_queries_ukr: { type: String },
  product_type: { type: String },
  price: { type: String },
  currency: { type: String },
  unit_of_measurement: { type: String },
  link_image: { type: String },
  quantity: { type: Number },
  group_name: { type: String },
  manufacturer: { type: String },
  country_of_production: { type: String },
  product_located: { type: String },
  name_characteristics1: { type: String },
  value_characteristics1: { type: String },
  name_characteristics2: { type: String },
  value_characteristics2: { type: String },
  name_characteristics3: { type: String },
  value_characteristics3: { type: String },
  name_characteristics4: { type: String },
  value_characteristics4: { type: String },
  name_characteristics5: { type: String },
  value_characteristics5: { type: String },
  name_characteristics6: { type: String },
  value_characteristics6: { type: String },
  name_characteristics7: { type: String },
  value_characteristics7: { type: String },
  name_characteristics8: { type: String },
  value_characteristics8: { type: String },
  name_characteristics9: { type: String },
  value_characteristics9: { type: String },
  name_characteristics10: { type: String },
  value_characteristics10: { type: String },
  name_characteristics11: { type: String },
  value_characteristics11: { type: String },
  name_characteristics12: { type: String },
  value_characteristics12: { type: String },
  name_characteristics13: { type: String },
  value_characteristics13: { type: String },
  name_characteristics14: { type: String },
  value_characteristics14: { type: String },
});

const ProductFeed = mongoose.model("ProductFeed", productFeedSchema);

export default ProductFeed;
